name: Build & Package

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Tag Name
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Download Dalamud Latest
        run: |
          wget https://raw.githubusercontent.com/goatcorp/dalamud-distrib/bab52566730dfe8b50645f01cbac4b395a8c3f66/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore
        
      - name: Build Project
        run: dotnet build --configuration Release AutoHook/AutoHook.csproj -p:AssemblyVersion=${{ env.tag }}

      - name: Package Artifact
        run: |
          # 创建构建目录并移动全部输出文件
          mkdir -p build_output
          cp -r AutoHook/bin/Release/AutoHook/* build_output/
          
          # 打包为带版本号的ZIP文件
          zip -r AutoHook-${{ env.tag }}.zip build_output
          
          # 在根目录生成校验文件
          sha256sum AutoHook-${{ env.tag }}.zip > checksum.sha256

      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: AutoHook_${{ env.tag }}
          path: |
            AutoHook-${{ env.tag }}.zip
            checksum.sha256
